# Generated by Django 5.2 on 2025-05-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='esstoque',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preço',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor'),
        ),
    ]
